[project]
name = "day11"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tanya-dotcm", email = "tanyajais235@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.142.2",
    "groq>=1.7.0",
    "pydantic>=2.13.5",
    "pypdf>=6.19.0",
    "python-docx>=1.2.0",
    "python-dotenv>=1.2.4",
    "uvicorn>=0.54.0",
]

[project.scripts]
day11 = "day11:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
